AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my-guy
      Runtime: go1.x
      CodeUri: ./deploy/my-guy.zip
      Environment:
        Variables: 
          S3_BUCKET: alexa_skills_lambda
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
